// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHe9XiShhzSc4ExTvqYpRDjl2lfUdFg7U',
    appId: '1:789283848967:web:a3f4b1bca8ca93d76e7ba2',
    messagingSenderId: '789283848967',
    projectId: 'mahjong-nanikiru-archive',
    authDomain: 'mahjong-nanikiru-archive.firebaseapp.com',
    storageBucket: 'mahjong-nanikiru-archive.firebasestorage.app',
    measurementId: 'G-LZ4V7S9MZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6-Bmb7hZAZqQM0bTyAAfVWt9Jse4eRyQ',
    appId: '1:789283848967:android:3736811042c1d31d6e7ba2',
    messagingSenderId: '789283848967',
    projectId: 'mahjong-nanikiru-archive',
    storageBucket: 'mahjong-nanikiru-archive.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaAg1VD70Rd7O5O2UibQpSiUuk9VCVM0',
    appId: '1:789283848967:ios:4cad5228a88f1e556e7ba2',
    messagingSenderId: '789283848967',
    projectId: 'mahjong-nanikiru-archive',
    storageBucket: 'mahjong-nanikiru-archive.firebasestorage.app',
    iosBundleId: 'com.example.zariMahjongLab',
  );
}
